
import { Schema, model } from "mongoose"; // import the schema and the model from the mongoose library

// the id, createdAt and the updatedAt will be generated by the model
const postSchema = new Schema({
    name: {
        type: String,
        required: true,
        trim: true
    },
    description: {
        type: String,
        required: true,
        trim: true
    },
    age: {
        type: Number,
        required: true,
        minLength: 1,
        maxLength: 100
    },     
},
    { timestamps: true }
)


const Post = model('Post', postSchema); // take the post converts to lowercase and the adds to the database as the collecttion  

export default Post;